/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Worker_Iperf3ExecutorWorker */

#ifndef _Included_de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Worker_Iperf3ExecutorWorker
#define _Included_de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Worker_Iperf3ExecutorWorker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Worker_Iperf3ExecutorWorker
 * Method:    iperf3Wrapper
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Worker_Iperf3ExecutorWorker_iperf3Wrapper
  (JNIEnv *, jobject, jobjectArray, jstring);

/*
 * Class:     de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Worker_Iperf3ExecutorWorker
 * Method:    iperf3Stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_fraunhofer_fokus_OpenMobileNetworkToolkit_Iperf3_Worker_Iperf3ExecutorWorker_iperf3Stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
